### PR TITLE
add new fuction EventsChanLength to expose the length of eventsChan

### PR DESCRIPTION
**Pull request by ogibayashi**
Hello. I'd like to add a new function to Amigo to expose the length of eventsChan. So that we can monitor it and know if our handler is processing events fast enough.
If `len(eventsChan)` is increasing, I think our handler is too slow to process the AMI events, we need some improvement.

### CODE REVIEW

**Comment by ogibayashi** [comment]
@ivahaev would you review this?

**Comment by ivahaev** [comment]
Yes, will look at this

**Review by ivahaev — APPROVED** [review]

**Comment by ivahaev** [comment]
Sorry for so long reaction, I don't have enough time to maintain this project.

**Comment by ogibayashi** [comment]
Thanks for your review. If you don't have time for maintaining this, I can do it because I'm using this project in our production.

**Pull request merged**
