### PR TITLE
Async AMI events support

### PR DESCRIPTION
**Pull request by wlredeye**
I've just added support of Async AMI events. With Async mode we receive events with both "Event" and "Response" fields, so for now code blocks on sending data to channel that no one listen on the other side here: 
`chanOutResponses <- data`

### CODE REVIEW

**Comment by ivahaev** [comment]
Hi,
Thank you for PR.

So, if event received with both "Event" and "Response" fields no data will be sent to `chanOutResponses` channel. I need to think about this part of code and make some tests.

**Comment by ivahaev** [comment]
Can you provide some samples of Async AMI events with both field?

**Comment by ivahaev** [comment]
Thank you, PR accepted

**Comment by wlredeye** [comment]
Here is AMI event example:

**Event**: OriginateResponse
Privilege: call,all
ActionID: 316407cb-f45a-48af-49d0-97036988f006
**Response**: Failure
Channel: SIP/1001
Context: full
Exten: 89039999999
Reason: 0
Uniqueid: <null>
CallerIDNum: 89039999999
CallerIDName: Click2call

And here why it blocks https://play.golang.org/p/JMvqOE6-up

**Comment by wlredeye** [comment]
Thank you!

**Comment by ivahaev** [comment]
I will rewrite this part to prevent any blocking.

**Pull request merged**
