### PR TITLE
Fix multi-line values

### PR DESCRIPTION
**Pull request by yaslama**

### CODE REVIEW

**Comment by ivahaev** [comment]
Hi,
When asterisk sends multiline values?

**Comment by yaslama** [comment]
Hi,
For instance:
ACTION: COMMAND
COMMAND: pjsip show endpoint 5200

**Comment by ivahaev** [comment]
So where is multiline value? :)

**Comment by yaslama** [comment]
The value is below: 

```
Endpoint:  <Endpoint/CID.....................................>  <State.....>  <Channels.>
    I/OAuth:  <AuthId/UserName...........................................................>
        Aor:  <Aor............................................>  <MaxContact>
      Contact:  <Aor/ContactUri..........................> <Hash....> <Status> <RTT(ms)..>
  Transport:  <TransportId........>  <Type>  <cos>  <tos>  <BindAddress..................>
   Identify:  <Identify/Endpoint.........................................................>
        Match:  <ip/cidr.........................>
    Channel:  <ChannelId......................................>  <State.....>  <Time.....>
        Exten: <DialedExten...........>  CLCID: <ConnectedLineCID.......>
==========================================================================================

 Endpoint:  5200                                                 Not in use    0 of inf
     InAuth:  5200/5200
        Aor:  5200                                               1
      Contact:  5200/sip:5200@192.168.x.x:5060         16203c786c Created       0.000
  Transport:  transport-udp             udp      0      0  0.0.0.0:5060


 ParameterName                      : ParameterValue
 =========================================================
 100rel                             : yes
 accountcode                        : 
 aggregate_mwi                      : true
 allow                              : (alaw)
 allow_subscribe                    : true
 allow_transfer                     : true
 aors                               : 5200
 auth                               : 5200
 bind_rtp_to_media_address          : false
 call_group                         : 
 callerid                           : <unknown>
 callerid_privacy                   : allowed_not_screened
 callerid_tag                       : 
 connected_line_method              : invite
 context                            : mycontext
 cos_audio                          : 0
 cos_video                          : 0
 device_state_busy_at               : 0
 direct_media                       : false
 direct_media_glare_mitigation      : none
 direct_media_method                : invite
 disable_direct_media_on_nat        : false
 dtls_ca_file                       : 
 dtls_ca_path                       : 
 dtls_cert_file                     : 
 dtls_cipher                        : 
 dtls_fingerprint                   : SHA-256
 dtls_private_key                   : 
 dtls_rekey                         : 0
 dtls_setup                         : active
 dtls_verify                        : No
 dtmf_mode                          : rfc4733
 fax_detect                         : false
 force_avp                          : false
 force_rport                        : true
 from_domain                        : 
 from_user                          : 
 g726_non_standard                  : false
 ice_support                        : false
 identify_by                        : username
 inband_progress                    : false
 language                           : 
 mailboxes                          : 
 media_address                      : 
 media_encryption                   : no
 media_encryption_optimistic        : false
 media_use_received_transport       : false
 message_context                    : 
 moh_suggest                        : default
 mwi_from_user                      : 
 mwi_subscribe_replaces_unsolicited : false
 named_call_group                   : 
 named_pickup_group                 : 
 one_touch_recording                : false
 outbound_auth                      : 
 outbound_proxy                     : 
 pickup_group                       : 
 record_off_feature                 : automixmon
 record_on_feature                  : automixmon
 rewrite_contact                    : false
 rpid_immediate                     : false
 rtp_engine                         : asterisk
 rtp_ipv6                           : false
 rtp_keepalive                      : 0
 rtp_symmetric                      : false
 rtp_timeout                        : 0
 rtp_timeout_hold                   : 0
 sdp_owner                          : -
 sdp_session                        : Asterisk
 send_diversion                     : true
 send_pai                           : false
 send_rpid                          : false
 set_var                            : 
 srtp_tag_32                        : false
 sub_min_expiry                     : 0
 t38_udptl                          : false
 t38_udptl_ec                       : none
 t38_udptl_ipv6                     : false
 t38_udptl_maxdatagram              : 0
 t38_udptl_nat                      : false
 timers                             : yes
 timers_min_se                      : 90
 timers_sess_expires                : 1800
 tone_zone                          : 
 tos_audio                          : 0
 tos_video                          : 0
 transport                          : transport-udp
 trust_id_inbound                   : false
 trust_id_outbound                  : false
 use_avpf                           : false
 use_ptime                          : false
 user_eq_phone                      : false
 voicemail_extension                :
```

**Comment by ivahaev** [comment]
Line delimiter in values is \n not  \r\n?

**Comment by yaslama** [comment]
True. It's \n in my tests. See also http://www.voip-info.org/wiki/view/Asterisk+Manager+API+Action+Command

**Comment by ivahaev** [comment]
Accepted. Thank you.

**Pull request merged**
